version: "3.4"

services:
  server:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
    - "8000:8000"
    volumes:
    - $PWD:/app
    - $PWD/.creds:/app/.creds
    depends_on:
    - db
    links:
    - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11
