version: "3"

services:
  api:
    build: ./
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_ENV=development
      - PORT=8000
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-app-creds.json
    ports:
    - "8000:8000"
    volumes:
    - ".:/app"
    - "./gcp-app-creds.json:/tmp/gcp-app-creds.json:ro"
    command: python app.py 
